import CreateRecipeForm from "@/components/CreateRecipeForm"
import Recipe from "@/components/Recipe"
import Head from "next/head"
import { useEffect, useState } from "react"

export default function Home() {
  const [recipies, setRecipies]: any = useState([
    {
      id: 0,
      name: "pizza",
      ingredients: [
        {
          name: "cheese",
          amount: 2,
          unit: "kg",
        },
        {
          name: "pepperoni",
          amount: 2,
          unit: "kg",
        },
      ],
      instructions:
        "What the crap dude! This is pizza\nHello World! Dude is this really what you are doing with this keyboard? Typing out this text?\nWhy would you use breaks here with some text, why not use a orem impusm generator?\nWhy would you do this to test it like this man.",
      fav: false,
    },
  ])

  return (
    <>
      <Head>
        <title>Recipe App - ReactJS || NextJS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='antialiased'>
        <header className='p-3 text-2xl bg-primary text-primary-content'>
          <h1>ReactJS Recipe App</h1>
        </header>

        <section className='max-w-5xl m-auto my-4 h-full flex gap-4'>
          <CreateRecipeForm setRecipies={setRecipies} recipies={recipies} />

          <section id='recipies' className='w-full'>
            <h2 className='text-3xl font-bold mb-2'>Recipes</h2>

            <div className='flex flex-col gap-2'>
              {recipies.map((recipe: any, i: any) => {
                return (
                  <Recipe key={i} recipe={recipe} recipies={recipies} setRecipies={setRecipies} />
                )
              })}
            </div>
          </section>
        </section>
      </main>
    </>
  )
}
