import CreateRecipeForm from "@/components/CreateRecipeForm"
import Head from "next/head"
import { useState } from "react"

export default function Home() {
  const [recipies, setRecipies] = useState([
    {
      name: "Instant Raman",
      ingredients: [
        {
          name: "ramen",
          amount: 1,
          unit: "kg",
        },
      ],
      instructions: "Hello World",
    },
  ])

  return (
    <>
      <Head>
        <title>Recipe App - ReactJS || NextJS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <header className='p-3 text-2xl bg-primary text-primary-content'>
          <h1>ReactJS Recipe App</h1>
        </header>

        <section className='max-w-5xl m-auto my-4 h-full flex gap-4'>
          <CreateRecipeForm />

          <section id='recipies'>
            {recipies.map((r, i) => {
              return (
                <div key={i}>
                  <h1>{r.name}</h1>
                </div>
              )
            })}
          </section>
        </section>
      </main>
    </>
  )
}

// User should be able to view recipes
// User should be able to add recipes
// User should be able to edit recipes
// User should be able to delete recipes
// User should be able to favorite recipes
// App should be hosted live
